smitchell-pc updates

diff --git a/sh/bin/as-release b/sh/bin/as-release
--- a/sh/bin/as-release
+++ b/sh/bin/as-release
@@ -252,11 +252,16 @@ function parse-args() {
                     else
                         timestring="${2}"
                     fi
-                    SINCE=$(date -d "${timestring}" "+%Y-%m-%d %H:%M:%S" 2>/dev/null)
-                    if [ $? -ne 0 ]; then
-                        echo "error: invalid date '${2}'" >&2
-                        help-usage >&2
-                        exit 1
+                    if [[ "${timestring}" == "auto" ]]; then
+                        # Then simply set SINCE to "auto"
+                        SINCE="auto"
+                    else
+                        SINCE=$(date -d "${timestring}" "+%Y-%m-%d %H:%M:%S" 2>/dev/null)
+                        if [ $? -ne 0 ]; then
+                            echo "error: invalid date '${2}'" >&2
+                            help-usage >&2
+                            exit 1
+                        fi
                     fi
                 fi
                 shift 2
@@ -483,14 +488,18 @@ function arg-type() {
     [[ "${arg_type}" != "unknown" ]]  # return 0 if arg_type is known, else 1
 }
 
-# Print a debug message if DEBUG=1 or write it to a log file if
-# DEBUG_LOG=<filepath> is set
+# @description Print debug information if $DEBUG or $DEBUG_LOG are set
+# @usage debug <message>
 function debug() {
+    local prefix timestamp
     if [[ "${DEBUG}" == "1" || "${DEBUG}" == "true" || -n "${DEBUG_LOG}" ]]; then
         timestamp="$(date '+%Y-%m-%d %H:%M:%S')"
-        prefix="\x1b[36m[${timestamp}]\x1b[0m \x1b[1;35m${FUNCNAME[1]}:${BASH_LINENO[0]}\x1b[0m --"
+        prefix="\033[36m[${timestamp}]\033[0m "
+        prefix+="\033[35m$(basename "${BASH_SOURCE[-1]}")"
+        [[ "${FUNCNAME[1]}" != "main" ]] && prefix+="\033[1m:${FUNCNAME[1]}()\033[0m"
+        prefix+="\033[32m:${BASH_LINENO[0]}\033[0m -- "
         printf "%s\n" "${@}" \
-            | sed -e "s/^/${prefix} /" \
+            | awk -v prefix="${prefix}" '{print prefix $0}' \
             | dd of="${DEBUG_LOG:-/dev/stderr}" conv=notrunc oflag=append status=none
     fi
 }
@@ -783,6 +792,19 @@ function main() {
 
         # Release each customization individually
         for customization in "${CUSTOMIZATIONS[@]}"; do
+            # Generate the commit message for the cherry-pick now since we'll filter for it if $SINCE is set to "auto"
+            local dest_customization="${DEST_CUSTOMIZATION:-${customization}}"
+            local commit_msg=$(
+                echo "${DEST_COMMIT_PATTERN}" \
+                    | awk -v cust="${dest_customization}" '
+                        {
+                            gsub("{{CUST}}", cust);
+                            print $0
+                        }
+                    '
+            )
+            debug "using commit message: ${commit_msg}"
+
             if [[ ${DO_VALIDATE} -eq 1 ]]; then
                 # Validate that the latest changes have been cherry-picked to test
                 echo -en "* validating ${C_MAGENTA}${S_BOLD}${customization}${S_RESET} is up-to-date in ${C_YELLOW}test${S_RESET} ... "
@@ -815,6 +837,18 @@ function main() {
             # Generate a list of all files committed under that Customization ID using ${GIT_LOG_OPTS}
             # note if there is a `--since` filter in ${GIT_LOG_OPTS}
             local since_filter
+            # If $SINCE is "auto", then use the date of the last promotion to the target repo's $DEST_BRANCH
+            if [[ "${SINCE}" == "auto" ]]; then
+                local last_promotion=$(git -C "${DEST_REPO}" log -1 --format=%at --grep="${commit_msg}" origin/"${DEST_BRANCH}")
+                debug "Last promotion of ${customization} to '${DEST_REPO}:${DEST_BRANCH}' was at ${last_promotion}"
+                if [[ ${last_promotion} -gt 0 ]]; then
+                    since_filter=" since ${C_YELLOW}${S_BOLD}$(date -d @${last_promotion} "+%Y-%m-%d %H:%M:%S")${S_RESET}"
+                    SINCE=$(date -d @${last_promotion} "+%Y-%m-%d %H:%M:%S")
+                    debug "updated SINCE to ${SINCE} -- ${since_filter}"
+                else
+                    since_filter=""
+                fi
+            fi
             if [[ "${SINCE}" != "" ]]; then
                 since_filter=" since ${C_YELLOW}${S_BOLD}${SINCE}${S_RESET}"
             fi
@@ -870,20 +904,10 @@ function main() {
                 fi
 
                 # Commit the files
-                local dest_customization="${DEST_CUSTOMIZATION:-${customization}}"
-                local commit_msg=$(
-                    echo "${DEST_COMMIT_PATTERN}" \
-                        | awk -v cust="${dest_customization}" '
-                            {
-                                gsub("{{CUST}}", cust);
-                                print $0
-                            }
-                        '
-                )
                 echo -e "* committing ${C_MAGENTA}${change_count}${S_RESET} change${s} to ${C_BLUE}${S_BOLD}${DEST_REPO_NAME}${S_RESET} as ${C_MAGENTA}${S_BOLD}${dest_customization}${S_RESET}"
                 (
                     echo-run git -C "${DEST_REPO}" add -A \
-                    && echo-run git -C "${DEST_REPO}" commit -m "${commit_msg}"
+                    && echo-run git -C "${DEST_REPO}" commit --no-gpg-sign -m "${commit_msg}"
                 )
                 if [[ ${?} -ne 0 ]]; then
                     echo -e "error: failed to commit files to ${C_BLUE}${S_BOLD}${DEST_REPO}${S_RESET}, aborting"
diff --git a/sh/bin/azsh b/sh/bin/azsh
--- a/sh/bin/azsh
+++ b/sh/bin/azsh
@@ -105,14 +105,14 @@ function parse-args() {
     REPO_ENC="$(urlencode "${REPO}")"
 
     # Debug infos
-    echo "SUBCOMMAND: ${SUBCOMMAND}" >&3
-    echo "SUBCOMMAND_ARGS: $(printf "%q " "${SUBCOMMAND_ARGS[@]}")" >&3
-    echo "POSITIONAL_ARGS: $(printf "%q " "${POSITIONAL_ARGS[@]}")" >&3
-    echo "ORGANIZATION: ${ORGANIZATION}" >&3
-    echo "PROJECT: ${PROJECT}" >&3
-    echo "REPO: ${REPO}" >&3
-    echo "PASS_NAME: ${PASS_NAME}" >&3
-    echo "TOKEN: ${TOKEN}" >&3
+    debug "SUBCOMMAND: ${SUBCOMMAND}"
+    debug "SUBCOMMAND_ARGS: $(printf "%q " "${SUBCOMMAND_ARGS[@]}")"
+    debug "POSITIONAL_ARGS: $(printf "%q " "${POSITIONAL_ARGS[@]}")"
+    debug "ORGANIZATION: ${ORGANIZATION}"
+    debug "PROJECT: ${PROJECT}"
+    debug "REPO: ${REPO}"
+    debug "PASS_NAME: ${PASS_NAME}"
+    debug "TOKEN: ${TOKEN}"
 }
 
 function help-full() {
@@ -577,8 +577,7 @@ function _agents_in_pool() {
     local response=$(
         curl "https://dev.azure.com/${ORGANIZATION_ENC}/_apis/distributedtask/pools/${pool_id}/agents?api-version=7.0" \
             --silent \
-            --user ":${TOKEN}" \
-            | python -m json.tool
+            --user ":${TOKEN}"
     )
 
     # Print out the agent information
@@ -710,7 +709,7 @@ function _subcommand_list-agents() {
         local agents=$(
             _agents_in_pool "${pool_id}" $'\t' \
                 | awk -v online="${online}" -v offline="${offline}" -v all_agents="${all_agents}" '{
-
+                        print $0;
                 }'
         )
         # printf "%s" "${pool_name}"
@@ -839,11 +838,11 @@ function _subcommand_run() {
         esac
     done
 
-    echo "pipeline_name: ${pipeline_name}" >&3
-    echo "branch: ${branch}" >&3
-    echo "variables: $(printf "%q " "${variables[@]}")" >&3
-    echo "parameters: $(printf "%q " "${parameters[@]}")" >&3
-    echo "wait: ${wait}" >&3
+    debug "pipeline_name: ${pipeline_name}"
+    debug "branch: ${branch}"
+    debug "variables: $(printf "%q " "${variables[@]}")"
+    debug "parameters: $(printf "%q " "${parameters[@]}")"
+    debug "wait: ${wait}"
 
     # Ensure a pipeline name was specified
     if [ -z "${pipeline_name}" ]; then
@@ -1143,6 +1142,29 @@ function _subcommand_pr-complete() {
             | python -m json.tool
 }
 
+# @description Create a pull request from / to the specified branches and auto-complete it
+# @usage pr <source branch> <target branch> [title] [description]
+function _subcommand_pr() {
+    local pr_id
+
+    # Create the pull request and get the id
+    while IFS= read line; do
+        # Check for the pull request id
+        if [[ -z "${pr_id}" && "${line}" =~ "pullRequestId" ]]; then
+            pr_id="$(echo "${line}" | sed -E 's/.*: ([0-9]+),/\1/')"
+        fi
+        echo "${line}"
+    done < <(_subcommand_pr-create "${@}")
+
+    # Set the pull request to auto-complete
+    if [[ -n "${pr_id}" ]]; then
+        _subcommand_pr-auto-complete "${pr_id}"
+    else
+        echo "error: failed to create pull request" >&2
+        return 1
+    fi
+}
+
 # @description Cancel a pull request
 # @usage pr-cancel <pr id>
 function _subcommand_pr-cancel() {
@@ -1173,138 +1195,169 @@ function _subcommand_pr-list() {
 # @description Print the usage message or the help message for a subcommand
 # @args [<subcommand>]
 function _subcommand_help() {
-    local subcommand="${1:-${POSITIONAL_ARGS[0]}}"
+    # Default arguments
+    local subcommands=()
+    local do_minimal=false
+
+    # Parse arguments
+    while [[ $# -gt 0 ]]; do
+        case "${1}" in
+            -m|--minimal)
+                do_minimal=true
+                shift 1
+                ;;
+            *)
+                subcommands+=("${1}")
+                shift 1
+                ;;
+        esac
+    done
+
+    debug "subcommands: ${subcommands[@]}"
+    debug "do_minimal: ${do_minimal}"
 
     # If no subcommand was specified, then print the help message
-    if [ -z ${subcommand} ]; then
+    if [[ ${#subcommands[@]} -eq 0 ]]; then
+        debug "Getting subcommands from ${0}"
         # Parse for all the subcommands
-        local subcommands=()
-        while read -r line; do
-            if [[ "${line}" =~ ^_subcommand_[A-za-z0-9_-]+" (" ]]; then
-                subcommands+=($(echo "${line}" | grep -oP "_subcommand_\K[a-z_-]+"))
-            fi
-        done < <(declare -f)
+        # local subcommands=()
+        # while IFS= read -r line; do
+        #     if [[ "${line}" =~ ^_subcommand_[A-za-z0-9_-]+" (" ]]; then
+        #         subcommands+=($(echo "${line}" | grep -oP "_subcommand_\K[a-z_-]+"))
+        #     fi
+        # done < "${0}"
+        readarray -t subcommands < <(
+            grep -oP "_subcommand_\K[a-z_-]+" "${0}" | sort | uniq
+        )
+        if ${do_minimal}; then
+            printf "%s\n" "${subcommands[@]}"
+            return 0
+        fi
         echo "usage: $(basename "${0}") <subcommand> [options]"
         echo
         echo "Available subcommands:"
-        printf " - %s\n" "${subcommands[@]}"
+        printf "    %s\n" "${subcommands[@]}"
         echo
         echo "For help with a specific subcommand, run:"
         echo "    $(basename "${0}") help <subcommand>"
     else
-        # Determine if the subcommand is an alias for another subcommand
-        local code=$(type "_subcommand_${subcommand}" 2>/dev/null)
-        if grep -qE "^    _subcommand_" <<< "${code}"; then
-            subcommand=$(echo "${code}" | grep -oP "^    _subcommand_\K[a-z_-]+")
-        fi
+        local is_first=true
+        for subcommand in "${subcommands[@]}"; do
+            ${is_first} && is_first=false || printf '\n---\n\n'
+            # Determine if the subcommand is an alias for another subcommand
+            local code=$(type "_subcommand_${subcommand}" 2>/dev/null)
+            if grep -qE "^    _subcommand_" <<< "${code}"; then
+                subcommand=$(echo "${code}" | grep -oP "^    _subcommand_\K[a-z_-]+")
+            fi
 
-        debug "subcommand: ${subcommand}"
+            debug "subcommand: ${subcommand}"
 
-        # Otherwise, use awk to print the help message for the specified
-        # subcommand
-        awk -v subcommand="${subcommand}" -v prog="$(basename "${0}")" '
-            BEGIN {
-                # used to track the current help name for multi-line fields
-                cur_help_name = "";
-            }
-            # Define a function that wraps text to a specified width
-            function wrap(text, width) {
-                # If the text is longer than the width, then wrap it
-                if (length(text) > width) {
-                    # Split the text into words
-                    split(text, words, " ");
-
-                    # Loop through the words and add them to the line
-                    line = "";
-                    for (i in words) {
-                        # If the line is empty, then add the word
-                        if (length(line) == 0) {
-                            line = words[i];
-                        } else if (length(line) + length(words[i]) + 1 <= width) {
-                            # If the line is not empty and the word will fit on
-                            # the line, then add the word
-                            line = line " " words[i];
-                        } else {
-                            # Otherwise, print the line and start a new line
-                            print line;
-                            line = words[i];
-                        }
-                    }
-
-                    # Print the last line
-                    print line;
-                } else {
-                    # Otherwise, just print the text
-                    print text;
-                }
-            }
-            {
-                # Store any lines that start with "# @"
-                if ($0 ~ /^# @/) {
-                    help_name = gensub(/^# @([a-z-]+).*/, "\\1", "g", $0);
-                    help_text = gensub(/^# @([a-z-]+) (.*)/, "\\2", "g", $0);
-                    cur_help_name = help_name;
-                    help[help_name] = help_text;
-                } else if ($0 ~ /^function/) {
-                    # If we find a function, either print the help message or
-                    # clear the help message
+            # Otherwise, use awk to print the help message for the specified
+            # subcommand
+            awk -v subcommand="${subcommand}" -v prog="$(basename "${0}")" '
+                BEGIN {
+                    # used to track the current help name for multi-line fields
                     cur_help_name = "";
-                    found_cmd = gensub(/^function _subcommand_([a-z_-]+).*/, "\\1", "g", $0);
-                    if (found_cmd == subcommand) {
-                        # If there is no help message, then say as much
-                        if (length(help) == 0) {
-                            exit 2;
+                }
+                # Define a function that wraps text to a specified width
+                function wrap(text, width) {
+                    # If the text is longer than the width, then wrap it
+                    if (length(text) > width) {
+                        # Split the text into words
+                        split(text, words, " ");
+
+                        # Loop through the words and add them to the line
+                        line = "";
+                        for (i in words) {
+                            # If the line is empty, then add the word
+                            if (length(line) == 0) {
+                                line = words[i];
+                            } else if (length(line) + length(words[i]) + 1 <= width) {
+                                # If the line is not empty and the word will fit on
+                                # the line, then add the word
+                                line = line " " words[i];
+                            } else {
+                                # Otherwise, print the line and start a new line
+                                print line;
+                                line = words[i];
+                            }
                         }
-                        # If there is a description, print and delete it
-                        if (help["description"]) {
-                            print wrap(help["description"], 80);
-                            delete help["description"];
-                        } else {
-                            delete help["description"];
-                        }
-                        # If there are args, print and delete them
-                        if (help["args"] != "") {
-                            print "usage: " prog " " subcommand " " help["args"];
-                            delete help["args"];
-                        } else {
-                            delete help["args"];
-                        }
-                        # Loop over the remaining help messages and print them
-                        for (help_name in help) {
-                            print help_name ": " help[help_name];
-                        }
-                        exit;
+
+                        # Print the last line
+                        print line;
                     } else {
-                        split("", help);
+                        # Otherwise, just print the text
+                        print text;
                     }
-                } else if (cur_help_name != "" && $0 ~ /^# /) {
-                    # If we are in a multi-line field, then append the line to
-                    # the current help message
-                    help_text = gensub(/^#\s+(.*)/, "\\1", "g", $0);
-                    help[cur_help_name] = help[cur_help_name] " " help_text;
                 }
-            }
-            END {
-                if (found_cmd != subcommand) {
-                    exit 1;
+                {
+                    # Store any lines that start with "# @"
+                    if ($0 ~ /^# @/) {
+                        help_name = gensub(/^# @([a-z-]+).*/, "\\1", "g", $0);
+                        help_text = gensub(/^# @([a-z-]+) (.*)/, "\\2", "g", $0);
+                        cur_help_name = help_name;
+                        help[help_name] = help_text;
+                    } else if ($0 ~ /^function/) {
+                        # If we find a function, either print the help message or
+                        # clear the help message
+                        cur_help_name = "";
+                        found_cmd = gensub(/^function _subcommand_([a-z_-]+).*/, "\\1", "g", $0);
+                        if (found_cmd == subcommand) {
+                            # If there is no help message, then say as much
+                            if (length(help) == 0) {
+                                exit 2;
+                            }
+                            # If there is a description, print and delete it
+                            if (help["description"]) {
+                                print wrap(help["description"], 80);
+                                delete help["description"];
+                            } else {
+                                delete help["description"];
+                            }
+                            # If there are args, print and delete them
+                            if (help["args"] != "") {
+                                print "usage: " prog " " subcommand " " help["args"];
+                                delete help["args"];
+                            } else {
+                                delete help["args"];
+                            }
+                            # Loop over the remaining help messages and print them
+                            for (help_name in help) {
+                                print help_name ": " help[help_name];
+                            }
+                            exit;
+                        } else {
+                            split("", help);
+                        }
+                    } else if (cur_help_name != "" && $0 ~ /^# /) {
+                        # If we are in a multi-line field, then append the line to
+                        # the current help message
+                        help_text = gensub(/^#\s+(.*)/, "\\1", "g", $0);
+                        help[cur_help_name] = help[cur_help_name] " " help_text;
+                    }
                 }
-            }
-        ' "${BASH_SOURCE[0]}"
-        local exit_code=${?}
-        case ${exit_code} in
-            0)
-                # Do nothing
-                ;;
-            1)
-                echo-stderr "error: no such subcommand '${subcommand}'"
-                ;;
-            2)
-                echo-stderr "error: no help message found for subcommand '${subcommand}'"
-                ;;
-            *)
-                echo-stderr "error: awk exited with code ${exit_code}"
-                ;;
-        esac
+                END {
+                    if (found_cmd != subcommand) {
+                        exit 1;
+                    }
+                }
+            ' "${BASH_SOURCE[0]}"
+            local exit_code=${?}
+            case ${exit_code} in
+                0)
+                    # Do nothing
+                    ;;
+                1)
+                    echo-stderr "error: no such subcommand '${subcommand}'"
+                    ;;
+                2)
+                    echo-stderr "error: no help message found for subcommand '${subcommand}'"
+                    ;;
+                *)
+                    echo-stderr "error: awk exited with code ${exit_code}"
+                    ;;
+            esac
+        done
     fi
     exit ${exit_code}
 }
@@ -1397,6 +1450,7 @@ function main() {
     fi
 
     # Run the subcommand
+    debug "running subcommand '${SUBCOMMAND}' with args '${SUBCOMMAND_ARGS[*]}'"
     "${subcommand_func}" "${SUBCOMMAND_ARGS[@]}"
 }
 
@@ -1404,11 +1458,4 @@ function main() {
 ## run #########################################################################
 ################################################################################
 
-[ "${BASH_SOURCE[0]}" == "${0}" ] && (
-    if [ -n "${DEBUG}" ]; then
-        exec 3>&2
-        main "${@}"
-    else
-        main "${@}" 3>/dev/null
-    fi
-)
+[ "${BASH_SOURCE[0]}" == "${0}" ] && main "${@}"
diff --git a/sh/bin/git-aha b/sh/bin/git-aha
--- a/sh/bin/git-aha
+++ b/sh/bin/git-aha
@@ -25,6 +25,7 @@ function help-full() {
     -w/--white              force white background (default)
     --html-header           include the HTML header (default)
     --no-header             do not include the HTML header
+    --(no-)show-command     (do not) show the command that was run
     -t/--title <title>      set the title of the HTML page
     -o/--output <file>      write the output to a file
     --log                   run `git log` (default)
@@ -46,10 +47,13 @@ function parse-args() {
     COLOR=true # true, false. this tool needs no "auto" option
     BACKGROUND="white" # white, black
     DO_HTML_HEADER=true
+    DO_SHOW_COMMAND=false
     GIT_CMD="log" # log, diff
     GIT_CMD_ARGS=() # -c color.ui=always, -c color.ui=never
     GIT_SUBCMD_ARGS=() # --no-pager, --stat, etc.
     AHA_ARGS=()
+    AHA_TITLE=""
+    COMMAND_FORMAT="%C(grey underline)> %C(green)git %C(teal)%subcmd %C(blue)%args"
     OUTPUT_FILE="/dev/stdout" # if empty, output to stdout
 
     # Loop over the arguments
@@ -83,8 +87,18 @@ function parse-args() {
             --no-header)
                 DO_HTML_HEADER=false
                 ;;
+            --show-command)
+                DO_SHOW_COMMAND=true
+                ;;
+            --no-show-command)
+                DO_SHOW_COMMAND=false
+                ;;
+            --command-style)
+                COMMAND_ANSI="${2}"
+                shift 1
+                ;;
             -t | --title)
-                AHA_ARGS+=("--title" "${2}")
+                AHA_TITLE="${2}"
                 shift 1
                 ;;
             -o | --output)
@@ -126,13 +140,17 @@ function parse-args() {
 
     # Use a standard, nice log format
     if [[ "${GIT_CMD}" == "log" ]]; then
-        # git log \
-        #    --format="%C(auto,green)%h  %C(auto,bold blue)% %<(20)%ad %C(auto,nobold yellow)%<(20)%al%C(auto,reset)%s%C(bold red)% gD% D%C(nobold white)" \
-        #    --date="format-local:%Y-%m-%d %H:%M:%S"
         GIT_SUBCMD_ARGS+=(
-            "--format=%C(auto,green)%h  %C(auto,bold blue)% %<(20)%ad %C(auto,nobold yellow)%<(20)%al%C(auto,reset)%s%C(bold red)% gD% D%C(nobold white)"
-            "--date=format-local:%Y-%m-%d %H:%M:%S"
+            --pretty="format:%C(auto,green)%h  %C(auto,bold blue)% %<(20)%ad %C(auto,nobold yellow)%<(20)%al%C(auto,reset)%s%C(bold red)% gD% D%C(nobold white)"
+            --date="format-local:%Y-%m-%d %H:%M:%S"
         )
+    fi
+
+    # Set the aha output file title
+    if [[ -n "${AHA_TITLE}" ]]; then
+        AHA_ARGS+=("--title" "${AHA_TITLE}")
+    else
+        AHA_ARGS+=("--title" "$(get-repo-name) | ${GIT_CMD}")
     fi
 
     # Set the positional arguments
@@ -140,19 +158,83 @@ function parse-args() {
 }
 
 
+## helpful functions ###########################################################
+################################################################################
+
+# @description Check if `aha` is installed and exit if not
+function check-aha() {
+    if ! command -v aha >/dev/null 2>&1; then
+        echo "error: \`aha\` is not installed" >&2
+        exit 1
+    fi
+}
+
+# @description Decode a url quoted string
+# @usage decode-url <string>
+function urldecode() {
+    local url_encoded="${1//+/ }"
+    printf '%b' "${url_encoded//%/\\x}"
+}
+
+# @description Determine the repo name from the git remote url
+# @usage get-repo-name
+function get-repo-name() {
+    local repo_url=$(git remote get-url "$(git remote | head -n 1)")
+    local repo_name=$(basename "${repo_url}" .git)
+    repo_name=$(urldecode "${repo_name}")
+    echo "${repo_name}"
+}
+
+
 ## main ########################################################################
 ################################################################################
 
 function main() {
+    # Parse the arguments
     parse-args "${@}"
 
-    # Run the git command
+    # Check for aha
+    check-aha
+
     debug "GIT_CMD_ARGS: ${GIT_CMD_ARGS[*]}"
     debug "GIT_CMD: ${GIT_CMD}"
     debug "GIT_SUBCMD_ARGS: ${GIT_SUBCMD_ARGS[*]}"
-    git "${GIT_CMD_ARGS[@]}" "${GIT_CMD}" "${GIT_SUBCMD_ARGS[@]}" \
-        | tr -d '\r' \
-        | aha "${AHA_ARGS[@]}" > "${OUTPUT_FILE}"
+
+    # Check if we should show the git command that is being run
+    local git_command_header=""
+    if ${DO_SHOW_COMMAND}; then
+        # Set up ansi colors for the git command
+        if ${DO_ANSI_COMMAND}; then
+            local c_start="\033[1;32m"
+            # local c_end="\033[0m"
+            # local c_arrow="\033[38;5;243m"
+            # local c_git="\033[32m"
+            # local c_cmd="\033[36m"
+            # local c_arg="\033[34m"
+            local c_reset="\033[0m"
+        fi
+        git_command_header=$(
+            printf "${c_start}${c_arrow}> ${c_git}git"
+            printf " ${c_cmd}%q" "${GIT_CMD}"
+            for arg in "${GIT_SUBCMD_ARGS[@]}"; do
+                # Skip formatting options
+                if [[ "${arg}" =~ "--"[a-z]+"=format" ]]; then
+                    continue
+                fi
+                printf " ${c_arg}%q" "${arg}"
+            done
+            printf "${c_reset}"
+        )
+    fi
+
+    # Run the git command
+    # Print the git command as a header
+    {
+        echo "${git_command_header}"
+        ${DO_SHOW_COMMAND} && echo
+        git "${GIT_CMD_ARGS[@]}" "${GIT_CMD}" "${GIT_SUBCMD_ARGS[@]}" \
+            | tr -d '\r'
+    } | aha "${AHA_ARGS[@]}" > "${OUTPUT_FILE}"
 }
 
 
