sh updates

diff --git a/sh/bin/as-release b/sh/bin/as-release
--- a/sh/bin/as-release
+++ b/sh/bin/as-release
@@ -84,9 +84,9 @@ EOF
     --validate            check whether the latest changes have been promoted.
                           assumes 'development', 'test', and 'release' branches
                           exist
-    --vdev <branch>       use <branch> as the dev branch for `--validate`
-    --vtest <branch>      use <branch> as the test branch for `--validate`
-    --vrelease <branch>   use <branch> as the release branch for `--validate`
+    --vdev <branch>       use <branch> as the dev branch for \`--validate'
+    --vtest <branch>      use <branch> as the test branch for \`--validate'
+    --vrelease <branch>   use <branch> as the release branch for \`--validate'
     --no-validate         do not check whether the latest changes have been
                           promoted
     --clean               remove uncommitted and untracked changes from the
@@ -96,6 +96,9 @@ EOF
     --pull                pull the latest changes from the source repo before
                           copying
     --no-pull             do not pull the latest changes from the source repo
+    --push                push the latest changes to the destination repo after
+                          copying
+    --no-push             do not push the latest changes to the destination repo
     --since <date>        only copy files committed after <date>
     --no-since            do not use --since/--after
     --until <date>        only copy files committed before <date>
@@ -139,6 +142,7 @@ function parse-args() {
     DO_COMMIT=0
     DO_CLEAN=1
     DO_PULL=1
+    DO_PUSH=0
     DO_VALIDATE=1
     VALIDATE_DEV="development"
     VALIDATE_TEST="test"
@@ -227,6 +231,14 @@ function parse-args() {
                 ;;
             --no-pull)
                 DO_PULL=0
+                shift 1
+                ;;
+            --push)
+                DO_PUSH=1
+                shift 1
+                ;;
+            --no-push)
+                DO_PUSH=0
                 shift 1
                 ;;
             --since | --until)
@@ -879,6 +891,18 @@ function main() {
                 fi
             fi
         done
+    fi
+
+    # Push the changes to the destination repo if requested
+    if [[ ${DO_PUSH} -eq 1 ]]; then
+        echo -en "* pushing to ${C_BLUE}${S_BOLD}${DEST_REPO_NAME}${S_RESET} ... "
+        echo-run git -C "${DEST_REPO}" push >/dev/null
+        if [[ ${?} -eq 0 ]]; then
+            echo -e "${C_GREEN}done${S_RESET}"
+        else
+            echo -e "error: failed to push to ${C_BLUE}${S_BOLD}${DEST_REPO}${S_RESET}, aborting"
+            exit 1
+        fi
     fi
 
     echo "* fin"
diff --git a/sh/bin/scratch b/sh/bin/scratch
--- a/sh/bin/scratch
+++ b/sh/bin/scratch
@@ -1,6 +1,12 @@
 #!/bin/bash
 #
 # Open a temporary file in the default editor
+#
+# TODO:
+# - For options like --list and --last, set a var to determine if the action
+#   should be taken, and then perform the action after the options are parsed.
+# - Update to allow multiple filepaths, and if an action calls for only one
+#   filepath, simply use the first specified.
 
 ## imports #####################################################################
 ################################################################################
@@ -13,7 +19,7 @@ include-source 'debug.sh'
 ################################################################################
 
 function help-usage() {
-    echo "usage: $(basename "${0}") [-h] [-e <editor>] [-d <dir>] [--clear|--rmdir|--list|<filename>]"
+    echo "usage: $(basename "${0}") [-hu] [-e <editor>] [-d <dir>] [--clear|--rmdir|--list|<filename>]"
 }
 
 function help-epilogue() {
@@ -29,16 +35,31 @@ function help-full() {
     echo "within the same day will use the same file."
     echo
     cat << EOF
-    -h                display usage
-    --help            display this help message
-    -e / --editor     the editor to use, defaults to the value of the EDITOR
-                      environment variable
-    -d / --dir <dir>  the directory to use for the scratch directory, defaults
-                      to the directory used by \`mktemp\`. if no argument is
-                      given, prints the scratch directory and exits
-    --clear           clear the scratch directory
-    --rmdir           remove the user's scratch directory
-    --list            list the files in the scratch directory
+    -h                  display usage
+    --help              display this help message
+    -e / --editor       the editor to use, defaults to the value of the EDITOR
+                        environment variable
+    -d / --dir <dir>    the directory to use for the scratch directory, defaults
+                        to the directory used by \`mktemp\`. if no argument is
+                        given, prints the scratch directory and exits
+    -u / --unique       guarantees a unique, unused scratch file
+    -l / --last         open the last modified scratch file
+    -v / --view <file>  view the specified scratch file
+    -e / --exec <cmd>   execute the specified command on the scratch file
+    --no-exec           do not execute the specified command on the scratch file
+    -I <string>         replace \`<string>\` with the scratch file in the
+                        command, e.g.: \`scratch -I {} --exec "cp {} ~/"\`
+    --clear             clear the scratch directory
+    --rm <file>         remove the specified file from the scratch directory
+    --rmdir             remove the scratch directory
+    --list              list the files in the scratch directory
+    --list-summary      list the files in the scratch directory with a summary
+                        of each file
+    --no-list-summary   do not list the files in the scratch directory with a
+                        summary of each file
+    --list-summary-length <n>
+                        the maximum length of the summary for each file,
+                        defaults to 50
 EOF
 }
 
@@ -48,6 +69,12 @@ function parse-args() {
     TMP_DIR=$(dirname "$(mktemp -u)")
     SCRATCH_DIR="${TMP_DIR}/scratch-$(id -u)"
     FILENAME=$(date +%Y%m%d)
+    DO_SUMMARY=1
+    DEFAULT_ACTION="scratch"
+    ACTION="${DEFAULT_ACTION}" # scratch, view, exec, clear, rmdir, list, rm
+    EXEC_CMD=""
+    EXEC_PLACEHOLDER=""
+    SUMMARY_LENGTH=50
     
     # Loop over the arguments
     while [[ ${#} -gt 0 ]]; do
@@ -73,10 +100,77 @@ function parse-args() {
                 SCRATCH_DIR="${2}"
                 shift
                 ;;
+            -v | --view)
+                if [[ -z "${2}" ]]; then
+                    echo-stderr "no file specified"
+                    exit 1
+                fi
+                FILENAME="${2}"
+                ACTION="view"
+                shift
+                ;;
+            -e | --exec)
+                if [[ -z "${2}" ]]; then
+                    echo-stderr "no command specified"
+                    exit 1
+                fi
+                EXEC_CMD="${2}"
+                ACTION="exec"
+                shift
+                ;;
+            --no-exec)
+                ACTION="${DEFAULT_ACTION}}"
+                ;;
+            -I)
+                if [[ -z "${2}" ]]; then
+                    echo-stderr "no placeholder specified"
+                    exit 1
+                fi
+                EXEC_PLACEHOLDER="${2}"
+                shift
+                ;;
             --list)
                 debug "listing files in scratch directory"
+                ACTION="list"
                 list-files "${SCRATCH_DIR}"
                 exit 0
+                ;;
+            --list-summary)
+                DO_SUMMARY=1
+                ;;
+            --no-list-summary)
+                DO_SUMMARY=0
+                ;;
+            --list-summary-length)
+                debug "setting summary length to: ${2}"
+                SUMMARY_LENGTH="${2}"
+                if ! [[ "${SUMMARY_LENGTH}" =~ ^[0-9]+$ ]]; then
+                    echo-formatted -r "invalid summary length: '${SUMMARY_LENGTH}'"
+                    exit 1
+                fi
+                shift
+                ;;
+            -u | --unique)
+                FILENAME=$(
+                    basename "$(generate-unique-filename "${SCRATCH_DIR}")"
+                )
+                ;;
+            -l | --last)
+                if [[ -f "${SCRATCH_DIR}/.last" ]]; then
+                    FILENAME=$(cat "${SCRATCH_DIR}/.last")
+                else
+                    # Get the last accessed file
+                    FILENAME=$(
+                        find "${SCRATCH_DIR}" -type f -name '[0-9]*' \
+                            -printf '%A@ %p\n' | sort -n | tail -1 | cut -f2- -d' '
+                    )
+                fi
+                if [[ -n "${FILENAME}" ]]; then
+                    FILENAME=$(basename "${FILENAME}")
+                else
+                    echo-warning "no scratch files found for $(whoami)"
+                    exit 1
+                fi
                 ;;
             --clear)
                 echo -n "clearing scratch directory ... "
@@ -99,6 +193,15 @@ function parse-args() {
                 rm -rf "${SCRATCH_DIR}"
                 exit ${?}
                 ;;
+            --rm)
+                if [[ -z "${2}" ]]; then
+                    echo-stderr "no file specified"
+                    exit 1
+                fi
+                FILENAME="${2}"
+                ACTION="rm"
+                shift
+                ;;
             *)
                 FILENAME="${1}"
                 shift
@@ -115,32 +218,146 @@ function parse-args() {
 function list-files() {
     local directory="${1:-${SCRATCH_DIR}}"
     debug "listing files in directory: ${directory}"
+    local filepaths filetype filesize summary ellipsis first_run
 
     # Ensure the directory exists
     if ! [[ -d "${directory}" ]]; then
-        echo-formatted -r "no scratch directory"
+        echo-formatted -r "no such directory '${directory}'"
         return 1
     fi
 
     # List the files in the directory
-    shopt -s nullglob
-    local filepaths=( "${directory}"/* )
-    debug "filepaths: ${filepaths[*]}"
-    if [[ ${#filepaths[@]} -eq 0 ]]; then
-        echo-formatted -y "no scratch files found for $(whoami)"
-        return 1
-    fi
-    (
-        for filepath in "${filepaths[@]}"; do
-            debug "filepath: ${filepath}"
-            local filetype="$(file -b "${filepath}")"
-            debug "filetype: ${filetype}"
-            if [[ "${filetype}" =~ 'ASCII text' ]]; then
-                local filename="$(basename "${filepath}")"
-                printf '%s\t%s\n' "${filename}" "$(date -r "${filepath}")"
+    (    
+        cd "${directory}"
+        shopt -s nullglob
+        filepaths=( * )
+        debug "filepaths: ${filepaths[*]}"
+        if [[ ${#filepaths[@]} -eq 0 ]]; then
+            echo-formatted -y "no scratch files found for $(whoami)"
+            return 1
+        fi
+        (
+            first_run=1
+            for filepath in "${filepaths[@]}"; do
+                debug "filepath: ${filepath}"
+                filetype=$(file -b "${filepath}")
+                debug "filetype: ${filetype}"
+                if [[ "${filetype}" =~ 'ASCII text'|'Unicode text' ]]; then
+                    if [[ "${first_run}" -eq 1 ]]; then
+                        first_run=0
+                        debug "first run"
+                    else
+                        echo
+                        debug "not first run"
+                    fi
+                    filesize=$(du -h "${filepath}" | cut -f1)
+                    if [[ "${filesize}" == '0' ]]; then
+                        # Check to see if the file size is measurable in bytes
+                        filesize="$(du -b "${filepath}" | cut -f1)B"
+                    fi
+                    # Read the first SUMMARY_LENGTH characters
+                    summary=$(dd if="${filepath}" skip=0 count=$((SUMMARY_LENGTH + 1)) bs=1 2>/dev/null)
+                    if [[ ${#summary} -eq $((SUMMARY_LENGTH + 1)) ]]; then
+                        # If the summary is SUMMARY_LENGTH + 1 characters long,
+                        # then cutting it down to SUMMARY_LENGTH characters will
+                        # result in trimming content, so add an ellipsis
+                        ellipsis='...'
+                    else
+                        ellipsis=''
+                    fi
+                    summary=$(echo ${summary:0:-1}"${ellipsis}")  # Trim to 50 characters and trim whitespace
+                    printf '\033[1m%s\033[0m\t\033[33m%s\033[0m\t\033[36m%s\033[0m\1: %s\n' \
+                        "${filepath}" \
+                        "${filesize}" \
+                        "$(date -r "${filepath}")" \
+                        "${summary}"
+                fi
+            done
+        ) | column -et -s $'\t' | tr '\1' '\n'
+    )
+}
+
+# @description Generates a unique filename in a directory
+# @usage generate-unique-filename [<directory>]
+function generate-unique-filename() {
+    directory="${1:-.}"
+
+    mktemp -u --tmpdir="${directory}" "XXXXXX"
+}
+
+# @description Convert bytes to human readable format
+# @usage bytes-to-human-readable [--precision <int>] <bytes>
+function bytes-to-human-readable() {
+    local units=( B KiB MiB GiB TiB PiB EiB ZiB YiB )
+    local unit_index=0
+    local unit
+    
+    # Default values
+    local bytes
+    local precision=2
+
+    # Parse arguments
+    while [[ ${#} -gt 0 ]]; do
+        case "${1}" in
+            --precision)
+                precision="${2}"
+                shift
+                ;;
+            *)
+                bytes="${1}"
+                ;;
+        esac
+        shift
+    done
+
+    # Convert bytes to human readable format
+    while [[ "${bytes}" -ge 1024 ]]; do
+        local whole=$((bytes / 1024))
+        if [[ ${precision} -gt 0 ]]; then
+            local part=$((bytes % 1024))
+            part=$((part * 100 / 1024))
+            if [[ ${part} -gt 0 ]]; then
+                bytes="${whole}.${part}"
             fi
-        done
-    ) | column -t -s $'\t'
+        else
+            bytes="${whole}"
+        fi
+        unit_index=$((unit_index + 1))
+    done
+    unit="${units[${unit_index}]}"
+    printf "%.${precision}f %s\n" "${bytes}" "${unit}"
+}
+
+# @description Generate a list of editor-specific options
+# @usage generate-scratch-editor-options <editor>
+function generate-scratch-editor-options() {
+    local editor="${1}"
+    local -n options="${2}"
+    options=()
+
+    case "${editor}" in
+        vim | vi)
+            options+=('-c' '"set ft=scratch"')
+            ;;
+        micro)
+            options+=('-autosave' '1')
+            ;;
+        *)
+            options=()
+            ;;
+    esac
+}
+
+# @description Convert a scratch filename to a scratch filepath
+# @usage get-scratch-filepath <filename>
+function get-scratch-filepath() {
+    local filename="${1}"
+    local filepath="${SCRATCH_DIR}/${filename}"
+
+    # Save the filename to ${SCRATCH_DIR}/.last
+    echo "${FILENAME}" > "${SCRATCH_DIR}/.last"
+
+    echo "${filepath}"
 }
 
 
@@ -158,13 +375,56 @@ function main() {
     # Create the scratch directory if it doesn't exist
     if [ ! -d "${SCRATCH_DIR}" ]; then
         mkdir -p "${SCRATCH_DIR}"
+        # Ensure the scratch directory is readable and writable only by the
+        # current user
+        chmod -R 600 "${SCRATCH_DIR}" 2>/dev/null
     fi
 
-    # Ensure the scratch directory is readable and writable only by the current user
-    chmod -R 700 "${SCRATCH_DIR}" 2>/dev/null
-
-    # Open that file in the default editor
-    "${EDITOR}" "${SCRATCH_DIR}/${FILENAME}"
+    # Do the thing
+    if [[ "${ACTION}" == "view" ]]; then
+        less "$(get-scratch-filepath "${FILENAME}")"
+        return ${?}
+    elif [[ "${ACTION}" == "list" ]]; then
+        list-files "${SCRATCH_DIR}"
+        return ${?}
+    elif [[ "${ACTION}" == "exec" ]]; then
+        # Replace EXEC_PLACEHOLDER with the scratch file path
+        if [[ -n "${EXEC_PLACEHOLDER}" ]]; then
+            EXEC_CMD=$(
+                awk -v filepath="$(get-scratch-filepath "${FILENAME}")" \
+                    -v placeholder="${EXEC_PLACEHOLDER}" \
+                    '{ gsub(placeholder, filepath); print }' \
+                    <<< "${EXEC_CMD}"
+            )
+        else
+            # If no placeholder is specified, append the scratch file path to
+            # the end of the command
+            EXEC_CMD=$(
+                printf '%s %q' \
+                    "${EXEC_CMD}" \
+                    "$(get-scratch-filepath "${FILENAME}")"
+            )
+        fi
+        debug "running command: \`${EXEC_CMD}\`"
+        eval "${EXEC_CMD}"
+        return ${?}
+    elif [[ "${ACTION}" == "scratch" ]]; then
+        generate-scratch-editor-options "${EDITOR}" editor_options
+        local scratch_cmd=(
+            "${EDITOR}"
+            "${editor_options[@]}"
+            "$(get-scratch-filepath "${FILENAME}")"
+        )
+        debug "running command: \`${scratch_cmd[@]}\`"
+        "${scratch_cmd[@]}"
+        return ${?}
+    elif [[ "${ACTION}" == "rm" ]]; then
+        rm -v "$(get-scratch-filepath "${FILENAME}")"
+        return ${?}
+    else
+        echo-formatted -r "invalid action: ${ACTION}"
+        return 1
+    fi
 }
 
 
