Enhance script execution and logging in shell utilities
* Add `is-bash` function to determine if a script is a bash script.
* Introduce `run-plugin` function for enhanced execution and logging of plugins.
* Update usage comments to reflect new argument options for `run-plugin`.
* Simplify `run-plugin` execution logic by removing complex piping and exit code handling.
* Add color and formatting support for plugin execution output.
* Standardize output formatting across different utility scripts.
* Remove redundant code and streamline error handling in `run-plugin`.

diff --git a/sh/bin/exwrapper b/sh/bin/exwrapper
--- a/sh/bin/exwrapper
+++ b/sh/bin/exwrapper
@@ -170,6 +170,29 @@ if ! declare -f debug-vars &>/dev/null; then
     }
 fi
 
+# Determine if a script is a bash script
+# usage: is-bash <filepath>
+function is-bash() {
+    local filepath="${1}"
+    local is_bash=false
+    local shebang
+
+    # Check the shebang
+    shebang=$(head -n 1 "${filepath}")
+    if [[ 
+        "${shebang}" == "#!/bin/bash"
+        || "${shebang}" == "#!/usr/bin/env bash"
+        || "${shebang}" =~ ^"#!".*[ /]bash(" ".*)?$
+    ]]; then
+        is_bash=true
+    else
+        # Check for a .sh extension
+        [[ "${filepath}" == *.sh ]] && is_bash=true
+    fi
+
+    ${is_bash}
+}
+
 # Function to run a command (default: wrapped command) with pretty debug output
 function run-cmd() {
     local command command_args
@@ -205,6 +228,98 @@ function run-cmd() {
 #  [command]
 #    # a comment
 #    command_setting_1 = value
+
+# Run a command and label stderr/stdout with the script name and stream label
+# Usage: run-plugin [--(no-)show-plugin-name] [--stdout-label <str>] [--stderr-label <str>] <script>
+function run-plugin() {
+    # Default options
+    local plugin_path="" plugin_name name_words pretty_name
+    local do_show_plugin_name=false
+    local stdout_label="out" stdout_prefix
+    local stderr_label="err" stderr_prefix
+
+    # Parse the arguments
+    while [[ ${#} -gt 0 ]]; do
+        case ${1} in
+            --show-plugin-name=*)
+                if [[ "${1}" == *"="* ]]; then
+                    do_show_plugin_name="${1#*=}"
+                else
+                    do_show_plugin_name=true
+                    shift 1
+                fi
+                shift 1
+                ;;
+            --no-show-plugin-name)
+                do_show_plugin_name=false
+                shift 1
+                ;;
+            --stdout-label=*)
+                if [[ "${1}" == *"="* ]]; then
+                    stdout_label="${1#*=}"
+                else
+                    stdout_label="${2}"
+                    shift 1
+                fi
+                shift 1
+                ;;
+            --stderr-label=*)
+                if [[ "${1}" == *"="* ]]; then
+                    stderr_label="${1#*=}"
+                else
+                    stderr_label="${2}"
+                    shift 1
+                fi
+                shift 1
+                ;;
+            -*)
+                echo "error: unknown option: ${1}" >&2
+                return 1
+                ;;
+            *)
+                plugin_path="${1}"
+                shift 1
+                ;;
+        esac
+    done
+
+    # Ensure the plugin path is set
+    if [[ -z "${plugin_path}" ]]; then
+        echo "error: no plugin path specified" >&2
+        return 1
+    fi
+
+    # Get the plugin name if requested
+    if ${do_show_plugin_name}; then
+        plugin_name=$(basename "${filepath}" | sed -E 's/\.[^.]+$//')
+        name_words=( ${plugin_name//[-_]/ } )
+        pretty_name+="${C_PLUGIN_NAME}${name_words[@]^}${S_RESET}"
+
+        # Add the plugin name to each stream prefix
+        stdout_prefix+="${C_PLUGIN_LABEL}(plugin)${S_RESET} "
+        stdout_prefix+="${pretty_name}: "
+        stderr_prefix+="${C_PLUGIN_LABEL}${C_ERROR}(plugin)${S_RESET} "
+        stderr_prefix+="${pretty_name}: "
+    fi
+
+    # If a label was provided, add it to the prefix
+    [[ -n "${stdout_label}" ]] && stdout_prefix+="${stdout_label}: "
+    [[ -n "${stderr_label}" ]] && stderr_prefix+="${stderr_label}: "
+
+    # Determine the 
+    # Run the script and print output in the format (depending on whether we're
+    # showing the plugin name and have stdout/stderr labels)
+    #   [(plugin) <filename>: ][<stderr_prefix>: ]<stderr>
+    #   [(plugin) <filename>: ][<stdout_prefix>: ]<stdout>
+    local exit_code=0
+    source "${plugin_path}" \
+        2> >(awk -v prefix="${stderr_prefix}" '{print prefix $0; fflush()}') \
+        1> >(awk -v prefix="${stdout_prefix}" '{print prefix $0; fflush()}')
+    exit_code=${?}
+
+    debug "run-plugin() exiting with ${exit_code}"
+    return ${exit_code}
+}
 
 # Get one or more sections of the config file
 function get-config-sections() {
@@ -561,12 +676,19 @@ if ${USE_COLOR}; then
     S_HIDDEN=$'\033[8m'  # not widely supported
     S_STRIKETHROUGH=$'\033[9m'  # not widely supported
     S_DEFAULT=$'\033[10m'
+
+    # Category colors
+    C_ERROR="${C_RED}"
+    C_WARNING="${C_YELLOW}"
+    C_PLUGIN_LABEL="${C_CYAN}${S_BOLD}"
+    C_PLUGIN_NAME="${C_CYAN}"
 else
     unset C_BLACK C_RED C_GREEN C_YELLOW C_BLUE C_MAGENTA C_CYAN C_WHITE C_RGB \
           C_DEFAULT_FG C_BLACK_BG C_RED_BG C_GREEN_BG C_YELLOW_BG C_BLUE_BG \
           C_MAGENTA_BG C_CYAN_BG C_WHITE_BG C_RGB_BG C_DEFAULT_BG S_RESET \
           S_BOLD S_DIM S_ITALIC S_UNDERLINE S_BLINK S_BLINK_FAST S_REVERSE \
-          S_HIDDEN S_STRIKETHROUGH S_DEFAULT
+          S_HIDDEN S_STRIKETHROUGH S_DEFAULT \
+          C_ERROR C_WARNING C_PLUGIN_LABEL C_PLUGIN_NAME
 fi
 
 
@@ -615,7 +737,7 @@ for EXW_PATH_PART in "${EXW_PATHS[@]}"; do
             filename=$(basename "${filepath}" | sed -E 's/\.[^.]+$//')
             pretty_name="${filename%.*}"
             pretty_name="${pretty_name//[-_]/ }"
-            pretty_name="(plugin) ${pretty_name}"
+            pretty_name="${C_CYAN}${S_BOLD}(plugin)${S_RESET} ${pretty_name}"
             # Run the script and print output in the format:
             #   <filename>: error: <stderr>
             #   <filename>: <stdout>
