check for bare repos

diff --git a/sh/bin/git-all b/sh/bin/git-all
--- a/sh/bin/git-all
+++ b/sh/bin/git-all
@@ -5,6 +5,7 @@
 
 include-source 'echo.sh'
 include-source 'text.sh'
+include-source 'shell.sh'
 
 ## usage functions #############################################################
 ################################################################################
@@ -34,7 +35,7 @@ EOF
 function parse-args() {
     # Default values
     VERBOSITY=1
-    MAXDEPTH=3
+    MAXDEPTH=2
     DIRECTORY=$(pwd)
     SUBCOMMAND=()
 
@@ -70,7 +71,9 @@ function parse-args() {
                     echo "error: maxdepth must be an integer" >&2
                     exit 1
                 fi
-                MAXDEPTH=${2}
+                # Set maxdepth to 1 greater than the specified value since we
+                # need to include the '.git' sub-directory in our search
+                MAXDEPTH=$((${2} + 1))
                 shift 2
                 ;;
             -d|--directory)
@@ -78,7 +81,7 @@ function parse-args() {
                 shift 2
                 ;;
             -*)
-                GIT_LOG_OPTS+=("${1}")
+                echo-stderr "error: unknown option: ${1}"
                 exit 1
                 ;;
             *)
@@ -99,13 +102,32 @@ function main() {
     local git_repos=()
     while IFS= read -r repo; do
         git_repos+=("${repo}")
-    done < <(find "${DIRECTORY}" -maxdepth ${MAXDEPTH} -type d -name '\.git' -printf '%h\n')
+    done < <(find -L "${DIRECTORY}" -maxdepth ${MAXDEPTH} -type d -name '\.git' -printf '%h\n')
+
+    # Find all bare git repositories in the specified directory
+    while IFS= read -r repo; do
+        # Make sure we haven't already found this repo
+        if ! is-in "${repo}" "${git_repos[@]}"; then
+            # Light check to make sure this is the root of a git repo
+            if [ -d "${repo}/objects" ] && [ -d "${repo}/hooks" ]; then
+                # More thorough check to make sure this is a bare git repo
+                if git -C "${repo}" rev-parse --is-bare-repository >/dev/null 2>&1; then
+                    git_repos+=("${repo}")
+                fi
+            fi
+        fi
+    done < <(find -L "${DIRECTORY}" -maxdepth ${MAXDEPTH} -type d -not \( -path "*/.git*" -prune \) -printf '%h\n')
+
+    echo-comment -V 3 "Found ${#git_repos[@]} git repositories:"
+    for repo in "${git_repos[@]}"; do
+        echo-formatted -V 3 "  ${repo}"
+    done
 
     # Run the specified git command in each repository
     for repo in "${git_repos[@]}"; do
-        echo-formatted -V 2 "$" -g "git -C '${repo}' ${SUBCOMMAND[@]}"
+        echo-formatted -V 2 "$" -g "git -C '${repo}' $(echo ${SUBCOMMAND[@]})"
         if [ ${VERBOSITY} -eq 0 ]; then
-            git -C "${repo}" "${SUBCOMMAND[@]}" >/dev/null 2>&1
+            git -C "${repo}" "${SUBCOMMAND[@]}" >/dev/null
         else
             git -C "${repo}" "${SUBCOMMAND[@]}"
         fi
