make git-update-timestamps work with directories and relative paths

diff --git a/sh/bin/git-update-timestamps b/sh/bin/git-update-timestamps
--- a/sh/bin/git-update-timestamps
+++ b/sh/bin/git-update-timestamps
@@ -58,6 +58,60 @@ function parse-args() {
     if [ ${#} -gt 0 ]; then
         FILEPATHS+=("${@}")
     fi
+
+    # For time savings
+    GIT_TOPLEVEL=$(git rev-parse --show-toplevel)
+
+    # If no filepaths were specified, use the git root
+    if [[ ${#FILEPATHS[@]} -eq 0 ]]; then
+        FILEPATHS=( "${GIT_TOPLEVEL}" )
+    fi
+}
+
+
+## helpful functions ###########################################################
+################################################################################
+
+# @description Update the timestamp of a file to its last author commit date
+# @usage update-timestamp <filepath> [<git options>]
+function update-timestamp() {
+    local filepath="${1}"
+    local git_opts=()
+    local timestamp
+
+    # Collect the remaining git log options
+    shift 1
+    if [[ ${#} -gt 0 ]]; then
+        git_opts=( "${@}" )
+    else
+        git_opts=( "${GIT_LOG_OPTS[@]}" )
+    fi
+
+    if [[ -z "${filepath}" ]]; then
+        echo "error: no filepath specified" >&2
+        return 1
+    fi
+
+    # Check that the filepath exists
+    ! [[ -e "${filepath}" ]] && return 1
+
+    timestamp=$(
+        git log \
+            "${git_opts[@]}" \
+            -n 1 \
+            --date=format:%Y%m%d%H%M.%S \
+            --pretty=format:%ad \
+            --date-order \
+            -- "${filepath}"
+    )
+
+    if [[ -z "${timestamp}" ]]; then
+        return 1
+    fi
+
+    touch -m -t "${timestamp}" "${filepath}"
+
+    echo "${timestamp}"
 }
 
 
@@ -67,21 +121,23 @@ function parse-args() {
 function main() {
     parse-args "${@}"
 
-    for file in "${FILEPATHS[@]}"; do
-        timestamp=$(
-            git log \
-                "${GIT_LOG_OPTS[@]}" \
-                -n 1 \
-                --date=format:%Y%m%d%H%M.%S \
-                --pretty=format:%cd \
-                --date-order \
-                -- "${file}"
-        )
-        if [ -z "${timestamp}" ]; then
-            echo "ERROR: skipping '${file}' -- no git log found" >&2
-            continue
+    local line sub_filepath timestamp
+    # Since ls-tree returns filepaths relative to the git root, ensure that we
+    # can convert those paths into paths relative to the current directory
+    local git_toplevel_rel=$(realpath --relative-to=. "${GIT_TOPLEVEL}")
+
+    for filepath in "${FILEPATHS[@]}"; do
+        # If the file is a directory, then descend recursively
+        if [[ -d "${filepath}" ]]; then
+            git ls-tree -r --full-tree HEAD | while read -r line; do
+                sub_filepath="${git_toplevel_rel}/${line#*$'\t'}"
+                printf '%s => ' "${sub_filepath}"
+                update-timestamp "${sub_filepath}"
+            done
+        else
+            printf '%s => ' "${filepath}"
+            update-timestamp "${filepath}"
         fi
-        touch -m -t "${timestamp}" "${file}"
     done
 }
 
