check for sqlite3 on start

diff --git a/sh/bin/sqlite-history b/sh/bin/sqlite-history
--- a/sh/bin/sqlite-history
+++ b/sh/bin/sqlite-history
@@ -1288,6 +1288,12 @@ function main() {
 
     local exit_code=${E_SUCCESS}
 
+	# Check if sqlite3 is installed
+	if ! command -v sqlite3 >/dev/null 2>&1; then
+		echo "error: sqlite3 not installed" >&2
+		return 1
+	fi
+
     # Verify and setup the database if necessary
     db-verify "${DB_PATH}" || db-setup
 
